sudo: false
cache:
  directories:
    - $HOME/.gradle
language: groovy
jdk:
- oraclejdk7
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: b/AVqnitsYwJLBFw+Uw+wCpQ2f8FjaxsvHj4FZChiDC/NiAovIbHi9fGfxyTH3brRsp7qBL4pS4YdOkHelJewtEZo/yaBTZHeE/z9FA09HRUslrlxUHLhcUbWFKlhGULwNkuNqoY7na/veTibms7YVVOj47j+FM2xSpHRMcE7PQ=
  - secure: UUgx6ybsrXdDBpv4A1YrsgeHCZjFAlHN0xOWjL8W61t+d+FHstoVIktsMsxtiu6c4S65WWw5xw5xbQ/34wL9bXF/LSm0ja4aF1A/ad8BcFO1kwEKJZjUtQfFBvskPOEGASAg8LdQ5zY+RouVBnYAVEhqWXsxXUq/pllMTuSTVvI=
  - secure: d5aYIyQOjGGMxGqJwyqcK2vC0ZqA5fwAUzdeneinc+vVn+GxjB8FqDlg+dhv0+2T4+p4ObvnNhDSKVpDLiDTodWWjArLJVlR6gR24HsWRJIvN3TNwdho5Z10VYo3lUZdpgtISkOJff3tkosHpjHMi5QHINd2AQzoBQ2Av9CxQCg=
  - secure: nln0too8DMfvqGpz6zalrTBp+mj81RF/HwF26qEMKN9P/9jqEPHTG44iefaWwxtYqTjuMQ7ofPo39VHuqDvj2VA9/ko5gNcmAbagHXhasQaWAXM5v1Ds3QiRMiXI+uNT6ZuGPn8WgyUaMH7ATF72AJqDsUTQeVi4RpXHlmJFGpk=
  - secure: rADAJOFUO2P6FqDn9Wlg4QfBvh6VvohrtV7JkPrz/D4lhlI7vqPG0gBjjs4ueUQwBjKNZPk0X57eKvAtrnAptyB3NqAgPxPn6jWf6OLB7MYB1TSzIpkvLrz57HHpBP0kSa5bulenL2S9E0AQDlP9/GiNb2FwLxDEHQSzxiBYddo=
  - secure: kIB+UhuoPHfgzeQJWp3gDTECLwCxvkCE8Q80jEnwj0z3gtaYU45D5L0n1h2h3Lp8Cpw3H+iF460g4C5etjohERsgwP/hjF1VrWYtXeBuLA8G8sEq116XmIsX+psr1NfkLIzMYPAqwOc+vL/M69DFnnue3/U9VlUO3rbODDL4mk4=
